jpudysz/react-native-unistyles

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
@jpudysz I've added these to better organize/categorize issues and give devs a hint to use Discussions for feature requests and discussions. 
Please rename `Ideas` topic on Discussions `Feature Requests` for better naming convention. There's no way to change the link `https://github.com/jpudysz/react-native-unistyles/discussions/categories/ideas` to `/feature-requests`, just fyi.
Let me know if templates needs to be changed
> chore: added GitHub issue and pull request templates

- src/types/mediaQueries.ts
Types in lib/types/mediaQueries.ts aren't very optimal for future changes. Every type is written by hand. We can use [template literal types](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html) to fix that issue.
> Simplify MediaQueries type

- package.json
- src/__tests__/normalizer.spec.ts
- src/utils/module.d.ts
- src/utils/normalizer.ts
- yarn.lock
Fixes  #52
Rather than _always_ normalizing colours, I've opted to only modify the input when required (ie. an `opacity` other than `1` is supplied) this means that the output isn't strictly as consistent, but will be faster and doesn't change the authors intent in the case an unsupported value is supplied that the browser still knows how to handle. (Like the new `color(display-p3 1 0.5 0)` formats)
Otherwise we can just pass the colour through as-is.
I've expanded and tweaked some of the existing tests to try to cover the new code path.
> Normalize all colors that React Native supports

- docs/src/content/docs/example/variants.mdx
- docs/src/content/docs/start/setup.mdx
Mention "as const" for theme to reduce the number of reported issues about types.
> docs: mention as const

- src/utils/breakpoints.ts
Fixes #64 
We shouldn't lowercase media queries as users may use camelCase like `superLarge`
Tested locally
> fix: lowercasing breakpoints as users may use camelCase

- src/utils/styles.ts
Reported in #67 . Users are unable to unset the shadowOffset & textShadowOffset styles
Tested locally on mobile and web
> fix: unsetting shadowOffset & textShadowOffset styles

- android/src/main/java/com/unistyles/UnistylesModule.kt
Fix android build when use React Native 0.73+ with Java 17. 
React Native recently added Nullable to javaScriptContextHolder:
`…UnistylesModule.kt:84:69 Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type JavaScriptContextHolder?
`
Fixed with Android sugestion
Build successful with react native 0.73+
Related links
[RN 0.72.7 ](https://github.com/facebook/react-native/blob/52904ffc420aaaf8a396a63c86b584b3967965a9/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactContext.java#L529)
[RN 0.73-rc.8](https://github.com/facebook/react-native/blob/6a4b434c8faa88c5b29ecf998c502a47fedc081b/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactContext.java#L542) Nullable …
> fix: android build in react native 0.73+

- src/useStyles.ts
For no registered theme we need one more dep in dependency array of `useStyles`.
Fixes #121
> fix: dependency array for no theme

- docs/src/content/docs/reference/compound-variants.mdx
Just a one-line typo correction in "Compound Variants" docs code snippet.
> docs: compound variants typo

- ios/UnistylesModule.mm
Initial window height reported for iOS was equal to window width. Fixes: #135
> fix: initial screen height for ios

- src/types/variants.ts
As discussed on Discord, using boolean variants should always result in "boolean" type rather than "true" or "false."
> feat: narrow down boolean variants

- docs/.astro/types.d.ts
- docs/astro.config.mjs
- docs/src/content/docs/reference/testing.mdx
- src/common.ts
- src/core/Unistyles.ts
- src/core/mocks/UnistylesMockedBridge.ts
- src/core/mocks/UnistylesMockedRegistry.ts
- src/core/mocks/UnistylesMockedRuntime.ts
- src/core/mocks/index.ts
> feat: add library mocks

- .github/workflows/ci.yml
- android/src/main/java/com/unistyles/UnistylesModule.kt
- package.json
- yarn.lock
Android devices with a notch (cutout) could receive two initial events regarding the insets. This occurred because `currentActivity` was null when Unistyles was calculating insets for `UnistylesRuntime`. This update should resolve the issue 💪
> feat: lateinit layout calculations for insets

- android/src/main/java/com/unistyles/Insets.kt
- android/src/main/java/com/unistyles/UnistylesModule.kt
- Don't trigger layout config change on app resume, assume that `systemInsets` may be nullable. Fixes #176 
- Call native destroy only when unistyles was initialized. Fixes #174
> fix: dont trigger layout config change on app resume

- src/core/UnistylesModule.ts
`updateTheme` doesn't trigger rerender for single registered theme
Fixes #179
> fix: updateTheme function for web

- docs/src/content/docs/reference/testing.mdx
As per https://github.com/jpudysz/react-native-unistyles/discussions/88#discussioncomment-9203131
Thought it would be worthwhile calling this out directly. For some reason using `NODE_ENV=test` wasn't working with my setup.
> docs: add jest.setup.js test example

- ios/platform/Platform_iOS.mm
Fixes https://github.com/jpudysz/react-native-unistyles/issues/208
I'm not an iOS developer, but I thought I'd take a stab at figuring out how to handle the iPadOS window frame sizing. I thought it'd be best to do it in a way that works across all iOS products to keep the code simple.
I think the solution here ended up being fairly clean and I was able to test on a physical iPad and an iPhone simulator to validate the breakpoints are working as intended on both operating systems.
> Support breakpoints when iPadOS window frame size changes

- .eslintrc
- examples/bare/ios/Podfile.lock
- examples/expo/src/components/StyleSheetBox.tsx
- examples/vision/assets/Bird.tsx
- examples/vision/assets/Cloud.tsx
- examples/vision/assets/Moon.tsx
- examples/vision/assets/Star.tsx
- examples/vision/assets/Sun.tsx
- examples/vision/metro.config.js
- examples/vision/package.json
- examples/vision/tsconfig.json
- examples/vision/visionos/Podfile
- examples/vision/visionos/Podfile.lock
- examples/vision/visionos/vision.xcodeproj/project.pbxproj
- examples/vision/visionos/vision/App.swift
- examples/vision/visionos/vision/AppDelegate.swift
- examples/vision/visionos/vision/Info.plist
- examples/vision/visionos/vision/PrivacyInfo.xcprivacy
- ios/platform/Platform_Shared.h
- ios/platform/Platform_Shared.mm
- ios/platform/Platform_visionOS.mm
- package.json
- tsconfig.json
- yarn.lock
> feat: support visionos with new core

- ios/platform/Platform_iOS.mm
I've noticed in the last couple of days a small issue with #209 when the app is backgrounded and then foregrounded https://github.com/jpudysz/react-native-unistyles/pull/209#issuecomment-2191845116
I was skeptical the fix would be as simple as checking the app state before computing the current screen size, but it seems to work! I've been trying to reproduce the jank while foregrounding one of my apps (that has a screen with more significant changes between breakpoints, which is where I first noticed this bug) and I haven't been able to reproduce at all!
Here's an example of the behavior cycling between 2 builds of the same app, the first with 2.8.0-beta1 and the second with the changes included in this PR:
https://share.icloud.com/photos/049KH9cdeymdJfySqtHKavPTA
> fix: avoid computing incorrect ios screen sizes when the app is backgrounded

- src/core/UnistyleRegistry.ts
- src/core/UnistylesRuntime.ts
Fixes issue with bad type returned from `UnistylesRuntime.fontScale`
> chore: parse fontscale back to float

- android/src/main/java/com/unistyles/Platform.kt
This PR fixes #230 as Unistyles was reading insets forced by other libraries like `react-native-keyboard-controller`.
In other words when keyboard is visible, then bottom insets is always 0. It also helps to create sticky inputs etc.
> feat: improve bottom insets

- android/src/main/java/com/unistyles/Platform.kt
Fixes #239 
Android's `rt.screen.height` takes in count edge-to-edge layout
> feat: update android screen hegiht with edge to edge layout

- cxx/UnistylesModel.cpp
- cxx/UnistylesModel.h
- examples/bare/README.md
- examples/bare/android/app/src/main/AndroidManifest.xml
- examples/bare/ios/Podfile.lock
- src/common.ts
- src/hooks/useUnistyles.ts
- src/types/unistyles.ts
Remove unnecessary C++ `dynamicTypeSize` event. It's unnecessary as `fontScale` event already triggers re-render
> feat: remove dynamicTypeSize event

- docs/src/content/docs/reference/unistyles-runtime.mdx
- examples/expo/src/examples/RuntimeScreen.tsx
- src/core/UnistylesModule.ts
- src/core/UnistylesRuntime.ts
- src/core/mocks/UnistylesMockedRuntime.ts
Implements `hairlineWidth` which is available in `UnistylesRuntime` and `miniRuntime`
> feat: implement hairlinewidth

- src/index.ts
- src/types/index.ts
- src/types/stylesheet.ts
I want to create some reusable Object and type them correctly
```
type Font = {
[key: string]: UnistyleText
}
export const fonts: Font = {
body: {
fontSize: 16,
fontWeight: 400,
lineHeight: 24
}
}
const stylesheet = createStyleSheet(theme => ({
body: {
...fonts.body
}
}));
```
It throws error if UnistyleText isn't used
> feat: export UniStyle(View|Text|Image) types

- docs/src/content/docs/reference/variants.mdx
The docs page for the [variants](https://reactnativeunistyles.vercel.app/reference/variants/) is not rendering the heading correctly for two of the sections due to a missing space.
> docs: fix variant headers

- src/index.ts
Export UnistylesTheme
I am implementing customised styles for border with some business logics.
I want to move the logic into a pure function. e.g
```
const getBorderColor = (theme: UnistylesThemes[keyof UnistylesThemes], focus: boolean, error: boolean) => {
if (error) {
return theme.colors.criticalDark;
}
...
}
```
I can mock UnistylesTheme from local via UnistylesThemes[keyof UnistylesThemes] but it's better to use UnistylesTheme directly.
> feat: export UnistylesTheme

- cxx/UnistylesImpl.cpp
Hello, thank you very much for creating such a great open-source project.
I installed version 2.9.1 to use react-native-unistyles. However, I encountered the following error while building the Android app.
```
[1/7] Building CXX object CMakeFiles/unistyles.dir/src/main/cxx/helpers.cpp.o
[2/7] Building CXX object CMakeFiles/unistyles.dir/.../node_modules/react-native-unistyles/cxx/UnistylesRuntime.cpp.o
[3/7] Building CXX object CMakeFiles/unistyles.dir/.../node_modules/react-native-unistyles/cxx/UnistylesModel.cpp.o
[4/7] Building CXX object CMakeFiles/unistyles.dir/.../node_modules/react-native-unistyles/cxx/UnistylesImpl.cpp.o
FAILED: CMakeFiles/unistyles.dir/.../node_modules/react-native-unistyles/cxx/UnistylesImpl.cpp.o
.gradle/caches/transforms-3/ef2d7697779c544a76e341d3d27be809/trans …
```
> fix: build fail on Android, cast float to double - support React Native 0.72

- docs/src/content/docs/reference/theming.mdx
Fixes #269 
I added this paragraph to explain why all the `theme` objects must share the same structure following the issue I opened. I believe this will make the documentation clearer.
> docs: add error example for theme object structure

- src/utils/styles.ts
It seems that at some point there was a change in the core of React Native, and we can't longer return following objects:
```tsx
<View
style={{
transform: [
{ scale: undefined }
]
}}
/>
```
but its possible with breakpoints eg.:
```tsx
{
transform: [
{ 
scale: {
md: 1,
lg: 2   
}
}
]
}
```
and our breakpoint is `sm`.
This PR simply filters transforms that are undefined.
This can for sure be reproduced with RN 0.74 and RN 0.75
> feat: remove undefined transforms

- android/src/main/cxx/platform.cpp
- android/src/main/cxx/platform.h
- android/src/main/java/com/unistyles/Platform.kt
- android/src/main/java/com/unistyles/UnistylesModule.kt
- cxx/UnistylesImpl.cpp
- cxx/UnistylesModel.h
- cxx/UnistylesRuntime.h
- docs/.astro/settings.json
- examples/expo/src/examples/HomeScreen.tsx
- src/core/UnistyleRegistry.ts
- src/types/unistyles.ts
Fixes #268 
and other reports about unnecessary re-renders.
From version 2.8.4 Unistyles is automatically animating bottom insets for Android. This can now be disabled with following config:
```tsx
UnistylesRegistry
.addConfig({
disableAnimatedInsets: true // android only
})
```
This feature already works differently on branch 3.x but anyone can disable it without any additional effort.
> feat: add option to disable animated insets

- package.json
- src/types/breakpoints.ts
- yarn.lock
> feat: flatten variants in case of never

- docs/src/content/docs/reference/variants.mdx
Hello, while reading the docs I came across what I thought was a syntax error. i wanted to fix this problem.
I don't know if I need to do the same for v3.0 branch
And thank you for this awesome library
> fix: syntax problem at docs/reference/variants.mdx

- docs/src/content/docs/examples/all.mdx
[https://www.unistyl.es/examples/all](https://www.unistyl.es/examples/all)
There is a broken link in the “Media Queries mixed with breakpoints” section
> docs: fix wrong link href

- docs/astro.config.mjs
- docs/src/content/docs/v3/references/web-classes.mdx
- docs/src/content/docs/v3/references/web-only.mdx
- docs/src/content/docs/v3/references/web-styles.mdx
- docs/src/styles/docs.css
> docs: web docs

- docs/src/content/docs/v3/guides/avoiding-keyboard.mdx
The "Avoiding Keyboard" documentation references the `rt` variable without including it in the `StyleSheet.create` function signature, causing confusion.
https://www.unistyl.es/v3/guides/avoiding-keyboard
> docs: add missing rt parameter

- src/web/registry.ts
- src/web/shadowRegistry.ts
Remove inline styles from the elements, since they're already parsed by unistyles and transformed into className
> feat: remove inline styles

- plugin/ref.js
Fixes passing refs via `forwardRef`
> feat: add support from refs passed via forwardRef

- android/build.gradle
Fixes #373 
The issue was hard to fix because I initially thought it was related to `CMakeLists.txt`, as the compiler was throwing numerous Nitro/C++ errors.  
After many attempts, I managed to build it by simply switching the JDK to version 17 via the Android Studio GUI.  
Unfortunately, this solution only worked after running `./gradlew clean` and manually removing some cached folders.  
For Expo users building with EAS, this approach wasn't viable. We needed a way to build **Unistyles 3.0** on Android out of the box.  
After further investigation, it turned out to be a simple issue with `abiFilters` used by React Native. I had tried adjusting it multiple times before, but Android’s caching system is far too aggressive.  
This patch will be included by default in `beta.2`, but if you …
> feat: make android compile

- src/core/withUnistyles/useDependencies.ts
- src/core/withUnistyles/withUnistyles.native.tsx
- src/core/withUnistyles/withUnistyles.tsx
- src/web/shadowRegistry.ts
Rerender native components wrapped in `withUnistyles` if any of dependencies has changed
This doesn't apply to web, since we're updating CSS instead of inline styles
> feat: add stylesheet dependencies to native withUnistyles

- src/core/createUnistylesComponent.tsx
- src/core/withUnistyles/withUnistyles.tsx
Correctly infer ref type when using `withUnistyles`
> fix: withUnistyles ref type

- cxx/core/HostStyle.cpp
- cxx/core/HostStyle.h
- cxx/hybridObjects/HybridShadowRegistry.cpp
- cxx/parser/Parser.cpp
- cxx/parser/Parser.h
- example/Button.tsx
- src/components/native/Pressable.native.tsx
Fixes #382  
Initially, we processed `variants` from `useVariants` in the Host Object of `StyleSheet`. Unfortunately, this was a mistake, as we shared a single `StyleSheet` instance across all components. This issue was not immediately apparent, but when one component re-rendered, it caused other (shared) styles in the single `StyleSheet` to update as well.  
This PR removes all parsing from the shared instance and moves it to the `ShadowTree`. As a bonus, I’ve added a small cache layer for getter of `styles`, which should improve performance since we no longer need to parse styles repeatedly.
> feat: stop processing unistyle in host object

- docs/src/content/docs/v3/references/stylesheet.mdx
Also got confused at first when I tried it, then remember that reanimated has some similar approach for some hooks
Related to https://github.com/jpudysz/react-native-unistyles/issues/415
> docs: warning about `theme` and `rt` usage with `.create` function

- src/components/native/Pressable.native.tsx
Addresses issues reported on Discord.  
For nested variants, `Pressable` was unable to resolve variants in the correct order.
Repro: https://github.com/akuul/unistyles-repo-repro
After:
https://github.com/user-attachments/assets/d195c565-67be-4ff5-ac73-b5cf82be3cfc
> feat: pressable nested variants

- cxx/parser/Parser.cpp
This issue was reported on Discord. 
While attempting to merge `Unistyle` with the `exotic` style, the `Unistyle` parser did not merge both styles because the `exotic` style was completely ignored.
This PR fixes the regression.
> fix: mergin exotic styles with unistyles

- cxx/core/HostStyle.cpp
- cxx/core/UnistyleWrapper.h
- src/core/withUnistyles/withUnistyles.native.tsx
Issue was reported on Discord.  
Wrapping a component with `withUnistyles` that uses `variants` had no effect because the Unistyle core was not attaching variants to nodes outside of the `ShadowRegistry`. This PR resolves the issue.
> feat: withUnistyles - accept variants before any native event

- cxx/hybridObjects/HybridShadowRegistry.cpp
- cxx/hybridObjects/HybridShadowRegistry.h
- src/components/Variants.tsx
- src/components/native/Pressable.native.tsx
Fixes an issue reported on Discord.  
If there are two text nodes with a parent <-> child relationship, there was a bug where the child's variants would override the parent's variants. This PR fixes that by ensuring variants are rolled out from the child to the parent, so every node now has the correct variant attached. It also supports cases where React Native `Text` nodes inherit parent styles, similar to regular React Native behavior.
For:
```tsx
<React.Fragment>
<ThemedText type="title">
Parent
<ThemedText>
Amother ThemedText
</ThemedText>
</ThemedText>
<ThemedText type="title">
Parent
<Text>
RN Text
</Text>
</ThemedText>
</React.Fragment>
```
We should get following result:
Requires regression testing before merging for #433
> feat: text nested variants

- plugin/__tests__/variants.spec.js
- plugin/variants.js
Fixes issue with `Property children[0] of JSXElement expected node to be of a type ["JSXText","JSXExpressionContainer","JSXSpreadChild","JSXElement","JSXFragment"] but instead got "ParenthesizedExpression"`
> fix: issue with useVariants and conditional children

- docs/src/pages/index.astro
When I go to https://www.unistyl.es/, my browser keeps offering to translate the page from Polish to English. It appears that the documentation is in English, so this PR sets the HTML language to English
> Set the landing page language to English

- docs/src/content/docs/v3/references/breakpoints.mdx
Currently, the code as suggested does not work.
```
Type '{ and: { height(hMin?: Nullable<MQValue> | undefined, hMax?: MQValue | undefined): symbol; }; }' is not assignable to type 'symbol'.ts(2322)
Hide.d.ts(3, 5): The expected type comes from property 'mq' which is declared here on type 'IntrinsicAttributes & { mq: symbol; } & { children?: ReactNode; }'
```
Additionally, at runtime, I receive this error:
```
Received invalid mq: [object Object] Error Component Stack
```
This updates the documentation to use the correct methods.
> Update Hide and Show documentation in breakpoints.mdx

- src/core/index.ts
- src/core/useProxifiedUnistyles/index.ts
- src/core/useProxifiedUnistyles/listener.native.ts
- src/core/useProxifiedUnistyles/listener.ts
- src/core/useProxifiedUnistyles/types.ts
- src/core/useProxifiedUnistyles/useProxifiedUnistyles.ts
- src/core/useUnistyles.ts
- src/core/withUnistyles/withUnistyles.native.tsx
- src/core/withUnistyles/withUnistyles.tsx
- src/index.ts
Easy reactive hook to access theme and runtime values from Unistyles 🦄
It uses a proxy under the hood to ensure that there are no unwanted rerenders
> feat: useUnistyles

- plugin/index.js
Quick typo fix on the babel plugin
> fix: typo on parameter name

- docs/src/content/docs/v3/other/babel-plugin.mdx
- example/babel.config.js
- plugin/import.js
- plugin/index.d.ts
- plugin/index.js
- plugin/stylesheet.js
- Enable type-safety on the plugin options
- Add additional doc for the options usage
- Add type reference in plugin source code
I guess next step would be to convert the whole plugin folder to typescript to have better type safety over babel/core/types
> feat: add types definitions for the babel plugin + extra docs

- docs/src/content/docs/v3/other/babel-plugin.mdx
- example/babel.config.js
I wasn't totally satisfied ahah
- Rename object to match official babel parameter name + interface
- Simplify example to only show one babel.config.js to make it easier to read
> docs: rename object to match official parameter name + simplify example

- cxx/hybridObjects/HybridStyleSheet.cpp
> fix: handle cssvars in native settings

- src/server/getServerUnistyles.tsx
The json quotes were being escaped as `&quot;` for this script, which is invalid syntax.  dangerouslySetInnerHTML fixes this.
> fix: unistyles state was escaped leading to invalid syntax

- src/components/native/ImageBackground.tsx
- src/core/createUnistylesElement.native.tsx
- src/core/createUnistylesElement.tsx
- src/core/createUnistylesImageBackground.tsx
- src/utils.ts
Copy native components properties like displayName, static methods (Image.getSize), etc.
fixes #532
fixes #529
> feat: copy native components properties

- components/native/Animated/package.json
- cxx/core/UnistylesRegistry.cpp
- cxx/core/UnistylesRegistry.h
- cxx/hybridObjects/HybridShadowRegistry.cpp
- package.json
- plugin/__tests__/playground.js
- plugin/consts.js
- plugin/exotic.js
- plugin/index.js
- src/components/native/Animated.tsx
- src/components/native/Pressable.native.tsx
- src/web/utils/unistyle.ts
- yarn.lock
To be tested on Android and Web.
Fixes: #524 
https://github.com/user-attachments/assets/f9434b2d-30a3-4abf-ac38-96070c0c5b99
> feat: add support for React Native Animated

- src/utils.ts
Native app doesn't allow iteration over getters
> fix: copy displayName and name manually

- components/native/NativeText/package.json
- components/native/NativeView/package.json
- expo-example/app/(tabs)/index.tsx
- package.json
- plugin/consts.js
- plugin/exotic.js
- plugin/index.js
- src/components/native/NativeText.native.tsx
- src/components/native/NativeText.tsx
- src/components/native/NativeView.native.tsx
- src/components/native/NativeView.tsx
Based on @hirbod snippet :D
- Check Android & web
Implements #461
> feat: add support for raw RTCView and RCTText

- README.md
- cxx/core/UnistylesRegistry.h
- cxx/hybridObjects/HybridStyleSheet.cpp
- cxx/parser/Parser.cpp
- docs/.astro/settings.json
- docs/astro.config.mjs
- docs/src/content/docs/v3/guides/merging-styles.mdx
- docs/src/content/docs/v3/other/babel-plugin.mdx
- docs/src/content/docs/v3/references/breakpoints.mdx
- docs/src/content/docs/v3/start/configuration.mdx
- expo-example/unistyles.ts
- plugin/index.d.ts
- plugin/index.js
- src/specs/StyleSheet/index.ts
> feat: native breakpoints - add config to use points instead of pixels

- docs/src/content/docs/v3/references/stylesheet.mdx
Not needed since https://github.com/jpudysz/react-native-unistyles/pull/553
> docs: remove non-needed runtime warning

- docs/src/content/docs/v3/guides/expo-router.mdx
I have noticed that the entry file can be a typescript file too. It might be confusing to readers if the doc only mention `.js` (which was my case).
Hope this helps!
> Improve expo-router instruction with typescript entry file

- cxx/common/Helpers.h
- cxx/parser/Parser.cpp
- expo-example/unistyles.ts
Fixes #609 
Native Views expect colors to be represented as `int`. In the current implementation we were missing parsing objects in arrays eg. for `boxShadow`.
Example:
```tsx
boxShadow: [
{
offsetX: 5,
offsetY: 5,
blurRadius: 5,
spreadDistance: 0,
color: "red",
}
]
```
was passed to ShadowTree as-is causing crash on Android and no shadow on iOS.
Right now it will look like this:
```tsx
boxShadow: [
{
offsetX: 5,
offsetY: 5,
blurRadius: 5,
spreadDistance: 0,
color: 2312311
}
]
```
> feat: parse colors in arrays

- cxx/core/UnistylesMountHook.cpp
- cxx/core/UnistylesMountHook.h
- cxx/hybridObjects/HybridStyleSheet.cpp
Remove additional shadow tree cloning in Mount hook. 
During the first beta it was necessary due to a lot of hacks and edge cases.
Now Unistyles runs smoothly without it and receives predictable behaviour.
Should also speed things up in benchmarks. Should be tested by wider group of testes.
Fixes #622
> feat: improve layout animations

- src/core/withUnistyles/withUnistyles.native.tsx
- src/core/withUnistyles/withUnistyles.tsx
- src/types/common.ts
Due to complex types parsing some Components types are not parsed correctly, for example `Rect` from `@shopify/react-native-skia`
Before:
After:
> fix: simplify withUnistyles types

- src/core/getClassname.ts
- src/core/withUnistyles/withUnistyles.tsx
- src/web/registry.ts
- src/web/shadowRegistry.ts
#654
Implement [proposal](https://github.com/jpudysz/react-native-unistyles/issues/654#issuecomment-2723829549) by @lundenmiika
Quick summary:
When component is wrapped with `withUnistyles` in a DOM it is wrapper with a `div` that has `display: contents` and applies generated className into it's children
```html
<div className="unistyles_t6zr8e375u" style="display: contents">
// Component
</div>
```
```css
.unistyles_t6zr8e375u > * {
// styles
}
```
https://github.com/user-attachments/assets/f23dc889-f180-4498-8316-47d6355bde9b
> feat: withUnistyles div support

- src/core/withUnistyles/withUnistyles.tsx
Using `withUnistyles` with only `contentContainerStyle` (without style prop) causes a TypeError:
```
Uncaught TypeError: Cannot convert undefined or null to object
at Object.getOwnPropertyDescriptors (<anonymous>)
```
```tsx
const UnistylesScrollView = withUnistyles(ScrollView);
<UnistylesScrollView contentContainerStyle={styles.navContainer}>
{/* content */}
</UnistylesScrollView>
```
- Add null check before accessing `narrowedProps.style` in `withUnistyles`
> fix: add nullcheck for empty styles in withUnistyles

- docs/astro.config.mjs
- docs/src/content/docs/v3/guides/react-compiler.mdx
- docs/src/content/docs/v3/other/babel-plugin.mdx
- docs/src/content/docs/v3/start/getting-started.mdx
- plugin/index.js
- plugin/src/index.ts
fixes #368 
React Compiler does all of the parsing on the `Program.enter` so we need to parse our `variants` before it happens
Video (running reproduction from #368 issue with updated plugin):
https://github.com/user-attachments/assets/7c6d145a-2f33-4977-af9f-6a71134cd013
> fix: unistyles with react-compiler

- docs/src/content/docs/v3/guides/server-side-rendering.mdx
- src/server/getServerUnistyles.tsx
- src/server/serialize.ts
- src/web/create.ts
- src/web/css/state.ts
- src/web/registry.ts
- src/web/state.ts
fixes #691
- update the SSR docs
- serialize config and inject this into client
Next.js lacks a single, guaranteed entry point for client-side code execution. To ensure our configuration is available from the start, we need to inject inject our config from the server side into window directly. To initialize our configuration, we make a optional init call within the StyleSheet.create, guaranteeing it runs early in the client-side lifecycle before any components are rendered.
SSR documentation was updated because:
- useServerInsertedHTML may be inserted multiple times without additional logic with a `useRef`
- unistyles caused hydration warnings due to adding className to the root html element
> fix: nextjs client components

- src/server/serialize.ts
fixes #698 
Now `serialize` function wraps every object's key with single quotes to prevent invalid js syntax
> fix: serialize config

- components/native/Image/package.json
There was a small changed missed in #695.
React Native is importing the web implementation and this breaks styling on native.
(have tested the change manually)
> fix: incorrect react-native export for Image

- src/web/css/core.ts
- src/web/utils/unistyle.ts
Wrong array of keys was passed to `allBreakpoints` argument, which caused CSS cascading issue when breakpoints were provided with a different order, example:
```
color: {
md: 'red', // (min-width: 500px)
xs: 'blue' // (min-width: 0px)
}
```
Now it parses correctly:
```
color: {
md: 'red', // (min-width: 500px)
xs: 'blue' // (min-width: 0px) and (max-width: 499px)
}
```
> fix: breakpoints order

- plugin/index.js
- plugin/src/index.ts
- plugin/src/stylesheet.ts
This is the first PR to add support for CommonJS in the Unistyles Babel plugin.  
This PR adds functionality to correctly detect StyleSheets.
Related to #707
> feat: add support for commonjs require to detect stylesheets
