src/createUnistyles.ts, src/hooks/index.ts, src/hooks/useDimensions.ts, src/hooks/useDimensions.web.ts, src/utils/styles.spec.ts, src/utils/styles.ts, tsconfig.json, yarn.lock
=> Nested objects

src/mediaQueries.ts
Tests seems to cover cases with spaces.
=> fix: media queries spaces

README.md
Added npm badges on README with useful information.
quick preview: https://github.com/jpudysz/react-native-unistyles/blob/44506d348b1d21709b0ffd211c8c03888721166d/README.md
=> docs: add npm badges on README.md

.github/ISSUE_TEMPLATE/bug-report.yml
- Fix typo
- Remove acknowledgements
=> chore: update ticket template

docs/src/content/docs/reference/use-styles.mdx, src/__tests__/createUnistyles.spec.tsx, src/createUnistyles.ts
=> feat: return breakpoint from useStyles

docs/src/content/docs/example/variants.mdx
I was struggling like, how the text its not getting bold... hahaha
Good job, congratulations for this library!! It makes us easier to develop!!
Fixing docs. variant example, just a little error.
=> Updated example from variants.mdx

src/hooks/useDimensions.web.ts
Reported in #61. This is regression fix for SSR. Will be available in 1.1.2
Update demo in https://github.com/jpudysz/react-native-unistyles-ssr-exmaple
=> chore: fix SSR - regression

src/utils/styles.ts
=> Fix default styles when selected variant has no styles

docs/src/content/docs/start/benchmarks.mdx
=> chore: benchmark spelling

docs/src/content/docs/start/setup.mdx
There is a small typo inside the start page
=> fix typo inside setup page

docs/src/assets/arrow-down.svg, docs/src/components/Hero.astro
Change scroll button color when it leaves "clouds" - based on screen aspect ratio
=> Fix scroll button on home page

docs/.astro/types.d.ts, docs/src/content/docs/start/migration-from-1.mdx, docs/src/content/docs/start/setup.mdx
As per discussion: https://github.com/jpudysz/react-native-unistyles/discussions/84
=> chore: highlight waring in the docs

docs/src/content/docs/reference/server-side-rendering.mdx
=> chore: update SSR docs

docs/astro.config.mjs, docs/src/content/docs/other/for-sponsors.mdx, docs/src/content/docs/v1/docs/start/setup.mdx
Add copy of v1 docs. Fixes #90
=> feat: add v1 docs

docs/src/content/docs/start/benchmarks.mdx
=> fix: docs typos

docs/src/content/docs/reference/plugins.mdx, docs/src/content/docs/reference/server-side-rendering.mdx
=> docs: typos

docs/.astro/types.d.ts, docs/astro.config.mjs, docs/src/content/docs/reference/debugging.mdx
Add secition about the debugging with react-native-unistyles
=> docs: add section about debugging

docs/src/content/docs/start/migration-from-1.mdx
Be more detailed in upgrade guide to run `pod install`
=> feat: mention in migration guide pod install

src/index.ts, src/types/index.ts
Fixes https://github.com/jpudysz/react-native-unistyles/discussions/128
=> feat: export UnistylesValues type

README.md, docs/src/components/Features.astro, docs/src/content/docs/examples/all.mdx, docs/src/content/docs/other/for-library-authors.mdx, docs/src/content/docs/reference/faq.mdx, docs/src/content/docs/reference/theming.mdx, docs/src/content/docs/start/setup.mdx, package.json
Add docs about react-native-windows support
=> docs: updates about windows support

package.json, react-native.config.js
Add config to enable autolinking on windows
=> feat: enable windows autolinking

src/common.ts, src/core/UnistyleRegistry.ts
=> chore: stop throwing errors for duplicated plugins in dev mode

examples/expo/src/examples/TypeScriptValidatorTest.tsx, src/utils/styles.ts
=> feat: add support for fontVariants

android/src/main/java/com/unistyles/Insets.kt, android/src/main/java/com/unistyles/UnistylesModule.kt
Fix initializing Unistyles in headless mode (Android)
Fixes #170
=> feat: headless unistyles

docs/src/content/docs/reference/variants.mdx
=> docs: Update variants.mdx

android/src/main/java/com/unistyles/UnistylesModule.kt, package.json
=> feat: update android colors on ui thread

android/src/main/java/com/unistyles/Insets.kt, package.json
[Android] Support `expo-navigation-bar` with absolute positioning
=> feat: [Android] Support expo-navigation-bar with absolute positioning

examples/bare/ios/Podfile.lock, package.json, src/core/UnistylesRuntime.ts
=> chore: replace destructuring with regular args passing

examples/macos/App.tsx, ios/UnistylesModule.h, ios/platform/Platform_Shared.mm, ios/platform/Platform_macOS.mm
- Adds support for macOS and new core
- Drops requiremenet for RN 0.74!
=> feat: add support for macos and RN 0.73

docs/astro.config.mjs, docs/src/content/docs/reference/unistyles-registry.mdx, examples/expo/src/examples/HomeScreen.tsx, src/core/UnistyleRegistry.ts, src/core/UnistylesModule.ts, src/types/unistyles.ts
=> feat: allow disabling debouncing for web

docs/.astro/settings.json, docs/src/content/docs/reference/faq.mdx
=> docs: mention reanimated with useanimatedkeyboard

src/core/mocks/UnistylesMockedRuntime.ts
=> feat: add mini runtime to mocks

README.md
Update README.md with new eslint plugin
=> docs: mention eslint plugin

docs/src/content/docs/reference/plugins.mdx, src/core/UnistylesRuntime.ts
Plugins will be removed in 3.0.
=> chore: deprecate plugins

android/src/main/cxx/platform.cpp, android/src/main/cxx/platform.h, android/src/main/java/com/unistyles/Platform.kt, cxx/UnistylesImpl.cpp, cxx/UnistylesModel.h, cxx/UnistylesRuntime.h, docs/astro.config.mjs, docs/src/content/docs/examples/all.mdx, docs/src/content/docs/reference/unistyles-runtime.mdx, examples/expo/app.json, examples/expo/package.json, examples/expo/src/examples/RuntimeScreen.tsx, ios/platform/Platform_iOS.mm, src/core/UnistylesModule.ts, src/core/UnistylesRuntime.ts, src/core/mocks/UnistylesMockedRuntime.ts, src/types/unistyles.ts, yarn.lock
Add support for `UnistlylesRuntime.rtl` and `rt.rtl` for web, android and ios.
=> feat: add support for rtl

src/core/UnistylesModule.ts
Adds support for updating `UnistlylesRuntime.rtl` and `rt.rtl` on web when the html `dir` attribute changes.
=> feat: support updating rtl on web

ios/platform/Platform_iOS.mm
=> feat: await initial values while initializing ios core

src/specs/StyleSheet/index.ts, src/specs/index.ts, web/index.ts, web/registry.ts, web/runtime.ts, web/state.ts
=> feat: ssr web

expo-example/App.tsx, web/convert/boxShadow.ts, web/convert/index.ts, web/convert/module.d.ts, web/convert/shadow.ts, web/convert/textShadow.ts, web/convert/transform.ts, web/convert/types.ts, web/convert/utils.ts, web/utils.ts
- convert transforms
- convert and validate text-shadow
- convert and validate box-shadow
https://github.com/user-attachments/assets/3888757e-9a14-49c2-9281-69be4c9679ff
=> feat: transform, box-shadow, text-shadow

src/types/stylesheet.ts, src/types/variants.ts, web/convert/index.ts, web/create.ts, web/useVariants.ts, web/utils.ts
Variants & Compound Variants for Web
Here is working example from [docs](https://github.com/jpudysz/react-native-unistyles/blob/main/examples/expo/src/examples/VariantsScreen.tsx) with extra `compoundVariant`
https://github.com/user-attachments/assets/7f55a893-fc6b-46f6-819c-9532fd52541d
=> feat: variants & compoundVariants

docs/.astro/settings.json, docs/astro.config.mjs, docs/src/content/docs/reference/unistyles-runtime.mdx, src/core/UnistylesRuntime.ts, src/core/mocks/UnistylesMockedRuntime.ts
=> feat: get theme by name

android/src/main/java/com/unistyles/Platform.kt
=> feat: prevent keyboard controller to report new ime insets when listener is disabled

cxx/common/Helpers.h, cxx/core/HostStyle.cpp, cxx/core/HostStyle.h, cxx/core/StyleSheet.h, cxx/core/StyleSheetRegistry.cpp, cxx/core/StyleSheetRegistry.h, cxx/core/UnistyleData.h, cxx/core/UnistylesCommitHook.cpp, cxx/core/UnistylesRegistry.cpp, cxx/core/UnistylesRegistry.h, cxx/hybridObjects/HybridShadowRegistry.cpp, cxx/hybridObjects/HybridStyleSheet.cpp, cxx/parser/Parser.cpp, cxx/parser/Parser.h, example/App.tsx, example/Typography.tsx, example/unistyles.ts, plugin/__tests__/dependencies.spec.js, plugin/__tests__/ref.spec.js, plugin/__tests__/stylesheet.spec.js, plugin/index.js, plugin/ref.js, plugin/style.js, plugin/stylesheet.js, plugin/variants.js, src/specs/ShadowRegistry/index.ts, src/specs/StyleSheet/index.ts
+ support multipple stylesheets
+ improve variants
=> feat: redesign parsing unistyles for platform events

README.md
I was confused about pod install process and thought maybe other could also get confused on installation step.
=> Update README.md for confusing install

src/types/stylesheet.ts, src/web/convert/index.ts, src/web/registry.ts, src/web/shadowRegistry.ts
Add support for custom classNames
=> feat: custom classname support

src/web/createUnistylesComponent.tsx, src/web/listener/listenToDependencies.ts, src/web/registry.ts, src/web/shadowRegistry.ts
=> feat: cache computed stylesheets

src/core/useBreakpoint.ts, src/core/useTheme.ts
=> fix: imports in web hooks

examples/bare/ios/Podfile.lock, examples/bare/package.json, package.json, yarn.lock
=> feat: upgrade example to 0.76, set min node version to 18

examples/bare/src/App.tsx, examples/tv/package.json, package.json, src/__tests__/styles.spec.ts, src/types/normalizer.ts, src/types/stylesheet.ts, src/utils/styles.ts, yarn.lock
Add support for new props from RN 0.76 `boxShadow` and `filter`.
Implements #320
=> feat: add support for new rn 0.76 css props

android/build.gradle
=> feat: exclude rn so

src/specs/StyleSheet/index.ts, src/types/common.ts, src/types/index.ts, src/web/convert/types.ts, src/web/create.ts, src/web/runtime.ts, src/web/state.ts, src/web/utils/common.ts
=> feat: unify web with cpp errors

.github/actions/setup/action.yml, .github/workflows/ci.yml
Update CI to use yarn + NodeJS 20 + `actions/setup-node@v4`
=> feat: new ci

plugin/__tests__/stylesheet.spec.js, plugin/style.js
=> fix: identifiers in pressables

plugin/__tests__/stylesheet.spec.js, plugin/import.js
=> feat: swap pressable implementation even for multiple imports from react-native

plugin/__tests__/dependencies.spec.js, plugin/index.js, plugin/stylesheet.js
=> feat: support detecting dependencies in multiple ifelse statements

plugin/__tests__/dependencies.spec.js, plugin/common.js
Fixes another babel issue about square brackets accessor.
Fixes #363
=> feat: correctly detect dependencies in arrays

plugin/import.js, plugin/index.js
=> feat: prevent traspiling components in node modules

src/core/createUnistylesComponent.tsx, src/core/index.ts, src/core/withUnistyles/index.ts, src/core/withUnistyles/types.ts, src/core/withUnistyles/withUnistyles.native.tsx, src/core/withUnistyles/withUnistyles.tsx, src/index.ts
=> feat: withUnistyles

cxx/common/Helpers.h, cxx/core/HostStyle.cpp, cxx/core/HostStyle.h, cxx/core/UnistyleWrapper.h, cxx/hybridObjects/HybridUnistylesRuntime.cpp, cxx/parser/Parser.cpp, example/App.tsx, plugin/__tests__/variants.spec.js, plugin/index.js, src/components/Variants.tsx, src/core/withUnistyles/useDependencies.ts, src/core/withUnistyles/withUnistyles.native.tsx, src/core/withUnistyles/withUnistyles.tsx
=> feat: improve withUnistyles on native

src/components/ScopedTheme.tsx, src/components/native/Pressable.tsx, src/core/passForwardRef.ts, src/core/withUnistyles/useDependencies.ts, src/core/withUnistyles/withUnistyles.native.tsx, src/hooks/useMedia.native.ts, src/specs/index.ts, src/web/index.ts, src/web/registry.ts, src/web/shadowRegistry.ts
=> fix: typings

docs/src/content/docs/v3/other/babel-plugin.mdx, package.json, plugin/__tests__/dependencies.spec.js, plugin/__tests__/ref.spec.js, plugin/__tests__/stylesheet.spec.js, plugin/__tests__/variants.spec.js, plugin/import.js
=> fix: invalid redirection paths

cxx/common/Helpers.h, cxx/core/HostStyle.cpp, cxx/core/HostStyle.h, cxx/core/UnistyleWrapper.h, cxx/parser/Parser.cpp, example/babel.config.js, expo-example/babel.config.js, plugin/import.js, src/core/withUnistyles/useDependencies.ts, src/core/withUnistyles/withUnistyles.native.tsx
=> fix: nested variants in pressables

src/components/native/Pressable.tsx, src/web/shadowRegistry.ts
=> fix: pressable web

src/web/runtime.ts
=> fix: circular dependency fail

components/native/ActivityIndicator/package.json, components/native/FlatList/package.json, components/native/Image/package.json, components/native/ImageBackground/package.json, components/native/KeyboardAvoidingView/package.json, components/native/Pressable/package.json, components/native/RefreshControl/package.json, components/native/ScrollView/package.json, components/native/SectionList/package.json, components/native/Switch/package.json, components/native/Text/package.json, components/native/TextInput/package.json, components/native/TouchableHighlight/package.json, components/native/TouchableOpacity/package.json, components/native/View/package.json, components/native/VirtualizedList/package.json, package.json, plugin/__tests__/dependencies.spec.js, plugin/__tests__/ref.spec.js, plugin/__tests__/stylesheet.spec.js, plugin/__tests__/variants.spec.js, plugin/import.js
Resolve exports issue that caused doubled bundle size and errors on web
=> fix: components exports

components/native/ActivityIndicator/package.json, components/native/FlatList/package.json, components/native/Image/package.json, components/native/ImageBackground/package.json, components/native/KeyboardAvoidingView/package.json, components/native/Pressable/package.json, components/native/RefreshControl/package.json, components/native/ScrollView/package.json, components/native/SectionList/package.json, components/native/Switch/package.json, components/native/Text/package.json, components/native/TextInput/package.json, components/native/TouchableHighlight/package.json, components/native/TouchableOpacity/package.json, components/native/View/package.json, components/native/VirtualizedList/package.json, src/web/shadowRegistry.ts, src/web/utils/unistyle.ts
Add `module` exports to components
=> fix: module exports

src/web/create.ts
=> fix: nested variants

package.json
Fixes: Native build due to missing Codegen headers
=> fix: codegen path

docs/src/content/docs/v3/start/migration-guide.mdx
Migration guide has some invalid code
=> docs: update display/hide migration guide

src/specs/StyleSheet/index.ts, src/web/css/state.ts, src/web/registry.ts, src/web/runtime.ts, src/web/shadowRegistry.ts, src/web/state.ts
=> feat: css vars

.github/workflows/ci.yml, .github/workflows/release.yml
=> ci: added release action

.github/workflows/release.yml
=> chore: release action

android/src/main/cxx/NativeUnistylesModule.cpp, android/src/main/cxx/NativeUnistylesModule.h, cxx/core/HashGenerator.cpp, cxx/core/HashGenerator.h, cxx/core/RNStyle.h, cxx/hybridObjects/HybridNavigationBar.cpp, cxx/hybridObjects/HybridNavigationBar.h, cxx/hybridObjects/HybridStatusBar.cpp, cxx/hybridObjects/HybridStatusBar.h, cxx/hybridObjects/HybridUnistylesRuntime.cpp, cxx/hybridObjects/HybridUnistylesRuntime.h, example/ios/Podfile.lock, ios/NativePlatform+ios.swift, ios/NativePlatform.swift, ios/UnistylesModuleOnLoad.mm
=> feat: upgrade nitro to 0.21

expo-example/app/_layout.tsx, expo-example/package.json, plugin/__tests__/imports.spec.js, plugin/index.js, yarn.lock
=> feat: ignore react-native like imports

src/core/withUnistyles/withUnistyles.tsx
=> fix: withUnistyles style types

src/components/native/Pressable.native.tsx, src/core/createUnistylesImageBackground.tsx
=> feat: update native pressable and imageBackground implementations

src/core/useUnistyles.ts
=> fix: useUnistyles theme type

src/core/createUnistylesElement.native.tsx
Create function that finds native ref for:
- VirtualizedList
- FlatList
- KeyboardAvoidingView
fixes #509
=> fix: find native ref of complex RN components

src/core/getClassname.ts
=> fix: nested array styles on the web

plugin/variants.js
=> fix: babel variants for react compiler

android/src/main/cxx/NativeUnistylesModule.cpp, android/src/main/java/com/unistyles/NativePlatform+android.kt, android/src/main/java/com/unistyles/NativePlatform+insets.kt, android/src/main/java/com/unistyles/NativePlatform+listener.kt, android/src/main/java/com/unistyles/UnistylesModule.kt
=> fix: crash on android reload

cxx/core/Unistyle.h, cxx/parser/Parser.cpp
=> fix: breakpoints dependencies reported before other depndencies

ios/NativePlatform+ios.swift
=> feat: ios add fallback to last known value when RCTPresentedViewController is not available

cxx/parser/Parser.cpp
=> fix: crash for bad access

docs/src/content/docs/v3/references/use-unistyles.mdx
=> docs: explain useUnistyles subscriptions

cxx/parser/Parser.cpp
=> feat: generate hash based on styleKey and stylesheet tag

plugin/index.js, plugin/stylesheet.js
=> feat: correctly detect any unistyles import

plugin/stylesheet.js
=> fix: new babel parser for empty arrow function

plugin/__tests__/stylesheet.spec.js, plugin/index.js, plugin/stylesheet.js
Fixes #571
See the linked issue for a description of the problem
=> fix: "detectedDependencies.map is not a function" when using "map" as style name

plugin/import.js, src/core/useProxifiedUnistyles/useProxifiedUnistyles.ts, src/core/withUnistyles/withUnistyles.native.tsx
=> fix: scoped themes on native for withUnistyles

android/src/main/java/com/unistyles/NativePlatform+insets.kt
=> feat: android get initial insets

cxx/core/HostUnistyle.cpp, cxx/core/HostUnistyle.h, example/ios/Podfile.lock
=> feat: implement unistyle cache

src/components/native/Pressable.native.tsx
=> feat: bring back registering pressables on ref

package.json, plugin/esbuild.js, plugin/index.d.ts, plugin/index.js
=> chore: adjust plugin code

docs/src/content/docs/v3/other/babel-plugin.mdx, example/babel.config.js
I went back and fourth on this and forget to revert back after changing the index.d.ts
=> fix: point to the correct definition file path

cxx/hybridObjects/HybridShadowRegistry.cpp, cxx/parser/Parser.cpp
=> fix: regression for scoped theme and multiple stylesheets

cxx/hybridObjects/HybridShadowRegistry.cpp
=> fix: regression for scoped themes and inline styles

android/src/main/java/com/unistyles/NativePlatform+insets.kt
This fixes #404 on the 3.x branch.  
It seems that calling:  
```kt
ViewCompat.setWindowInsetsAnimationCallback(view, null)
```  
breaks other subscribers, e.g. `react-native-reanimated`. Instead, Unistyles will use an internal flag to stop updating the listener.
=> feat: android - dont stop listening to ime events

cxx/parser/Parser.cpp
=> chore: regression for unistyles cache

cxx/hybridObjects/HybridUnistylesRuntime.cpp
=> feat: add condition before sending unistyles theme change event

plugin/__tests__/dependencies.spec.ts, plugin/src/stylesheet.ts
=> feat: allow destructuing insets with ime in logical expressions

cxx/hybridObjects/HybridUnistylesRuntime.cpp, src/core/createUnistylesElement.native.tsx, src/core/createUnistylesImageBackground.tsx
=> feat: add cleanup with ref callbacks, theme change regression

cxx/parser/Parser.cpp
=> feat: parse correcrly props with arrays in variants and compound variants

src/core/withUnistyles/withUnistyles.native.tsx
=> feat: withUnistyles allow for nested arrays

docs/astro.config.mjs, docs/package.json, yarn.lock
=> feat: generate llms.txt for Unistyles

docs/astro.config.mjs, docs/src/content/docs/v3/llms/info.mdx
=> docs: mention llms.txt

src/web/runtime.ts, src/web/state.ts, src/web/utils/unistyle.ts
=> fix: breakpoints and themes are optional on the web

src/web/registry.ts
=> fix: scoped theme for web

docs/src/content/docs/v3/guides/server-side-rendering.mdx
=> docs: pages router ssr docs

src/core/useProxifiedUnistyles/useProxifiedUnistyles.ts
=> feat: add sub proxy for ime while listening for useUnistyles hook

src/components/native/Pressable.native.tsx
=> fix: crash in pressable release mode

plugin/index.js, plugin/src/consts.ts
=> fix: add default autoprocess paths for lib

cxx/core/HostUnistyle.cpp
=> feat: create stylesheet copy instead of overriding shared instance

cxx/core/HostUnistyle.cpp, expo-example/app/(tabs)/index.tsx
=> fix: crash with dynamic function

plugin/src/index.ts
=> feat: accept upprcased style key

src/web/registry.ts, src/web/shadowRegistry.ts
=> fix: delay removing listeners

plugin/index.js, plugin/src/index.ts, plugin/src/stylesheet.ts
=> feat: handle assignments in babel paths

cxx/core/UnistylesRegistry.h
=> feat: add support for xcode 16.3

cxx/common/Helpers.h
=> feat: accept numeric variants on jsi side

src/core/withUnistyles/withUnistyles.native.tsx
=> fix: regression inline styles for withUnistyles

cxx/core/UnistylesCommitHook.cpp, cxx/core/UnistylesRegistry.cpp, cxx/hybridObjects/HybridStyleSheet.cpp, cxx/parser/Parser.cpp, cxx/shadowTree/ShadowTrafficController.h, expo-example/package.json, src/components/native/Pressable.native.tsx, src/core/createUnistylesElement.native.tsx, src/core/createUnistylesImageBackground.tsx, src/core/passForwardRef.ts, src/specs/ShadowRegistry/index.ts, yarn.lock
=> feat: improve locking and cleanups

docs/src/content/docs/v3/start/getting-started.mdx
=> docs: update beta to rc

nitrogen/generated/android/c++/JUnistyleDependency.hpp, nitrogen/generated/android/kotlin/com/margelo/nitro/unistyles/UnistyleDependency.kt, nitrogen/generated/ios/swift/UnistyleDependency.swift, nitrogen/generated/shared/c++/UnistyleDependency.hpp, plugin/index.js, plugin/src/stylesheet.ts, src/core/useProxifiedUnistyles/useProxifiedUnistyles.ts, src/specs/NativePlatform/NativePlatform.nitro.ts, tsconfig.json
=> feat: babel assign dependency number for rtl

README.md, docs/src/content/docs/v3/start/getting-started.mdx
=> chore: change version tag from rc to next

android/src/main/java/com/unistyles/UnistylesModule.kt
Port fix about increasing android listener timeout from branch 3.x
=> feat: increse android listner timeout 2.x

src/web/runtime.ts
=> fix: emit adaptive themes change event, toggle adaptiveThemes after setting theme to prevent error
